# COlumn Transform

In [8]:
#import require library
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [5]:
# load the data set
data = pd.read_csv('covid_toy.csv')

In [6]:
data.sample(5)

    age  gender  fever   cough       city has_covid
68   54  Female  104.0  Strong    Kolkata        No
89   46    Male  103.0  Strong  Bangalore        No
4    65  Female  101.0    Mild     Mumbai        No
11   65  Female   98.0    Mild     Mumbai       Yes
52   47  Female  100.0  Strong  Bangalore       Yes

In [7]:
data.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [33]:
data.shape

(100, 6)

In [38]:
x_train,x_test,y_train,y_test = train_test_split(data.drop(columns=['has_covid']),data['has_covid'],test_size=0.2,random_state=43)

In [40]:
x_train.head()

    age  gender  fever   cough       city
44   20    Male  102.0  Strong      Delhi
12   25  Female   99.0  Strong    Kolkata
78   11    Male  100.0    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata

In [41]:
colum_transformer = ColumnTransformer(transformers=[('tf1',SimpleImputer(),['fever']),
('tf2',OneHotEncoder(drop='first',sparse_output=False,dtype=int),['gender','city']),
    ('tf3',OrdinalEncoder(categories=[['Mild','Strong']]),['cough'])]
    ,remainder='passthrough')

In [43]:
x_data=colum_transformer.fit_transform(x_train)

In [44]:
x_test = colum_transformer.transform(x_test)

In [48]:
x_data

array([[102.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [ 99.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  25.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [100.70833333,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  79.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  55.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  82.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [100.70833333,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  71.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  26.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [100.70833333,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  34.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  50.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  13.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  56.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  27.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  14.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  33.        ],
       [100.70833333,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  75.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  68.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  51.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   5.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  75.        ],
       [100.70833333,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  34.        ],
       [100.70833333,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  23.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [100.70833333,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  82.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  31.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  83.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   8.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  81.        ],
       [100.70833333,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  20.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  16.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  10.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  47.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  66.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  24.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  24.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  65.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  59.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  69.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  74.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   5.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  82.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,   5.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  47.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  15.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  51.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   6.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  40.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  11.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  69.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  23.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  44.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  42.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  54.        ]])